pre-commit:
  parallel: true
  commands:
    oxlint:
      glob: '*.{js,mjs,ts}'
      run: bunx oxlint --fix {staged_files}
      stage_fixed: true
    oxfmt:
      glob: '*.{js,mjs,ts,json,jsonc}'
      run: bunx oxfmt --no-error-on-unmatched-pattern {staged_files}
      stage_fixed: true
    typecheck:
      run: bun run typecheck
    test:
      run: bun test --pass-with-no-tests
